version: '3.9'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.2
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      my_custom_network:
        ipv4_address: 192.168.1.3
networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.1.0/24"

